# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "dynamo-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-http = { path = "../../build/aws-sdk/sdk/aws-http" }
aws-sdk-dynamodb = { path = "../../build/aws-sdk/sdk/dynamodb" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util", "rustls"] }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
aws-smithy-types = { path = "../../build/aws-sdk/sdk/aws-smithy-types" }
aws-smithy-protocol-test = { path = "../../build/aws-sdk/sdk/aws-smithy-protocol-test" }
aws-types = { path = "../../build/aws-sdk/sdk/aws-types" }
bytes = "1"
# TODO(https://github.com/awslabs/smithy-rs/issues/1044) v3.5 has an unmaintained dependency, upgrade this when possible
criterion = { version = "0.3.5" }
futures-util = "0.3"
http = "0.2.4"
serde_json = "1"
tokio = { version = "1", features = ["full", "test-util"]}
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
tokio-stream = "0.1.8"

[[bench]]
name = "deserialization_bench"
harness = false

[[bench]]
name = "serialization_bench"
harness = false
