# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "polly-tests"
version = "0.1.0"
authors = ["John DiSanti <jdisanti@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
aws-http = { path = "../../build/aws-sdk/sdk/aws-http"}
aws-sdk-polly = { path = "../../build/aws-sdk/sdk/polly" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util", "rustls"] }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
bytes = "1"
http = "0.2.3"
tokio = { version = "1", features = ["full"]}
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
