[package]
name = "transcribestreaming"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
edition = "2018"

[dev-dependencies]
async-stream = "0.3"
aws-http = { path = "../../build/aws-sdk/sdk/aws-http" }
aws-sdk-transcribestreaming = { path = "../../build/aws-sdk/sdk/transcribestreaming" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util", "rustls"] }
aws-smithy-eventstream = { path = "../../build/aws-sdk/sdk/aws-smithy-eventstream" }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
bytes = "1"
futures-core = "0.3"
hound = "3.4"
http = "0.2.3"
serde_json = "1"
tokio = { version = "1", features = ["full", "test-util"] }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
