[package]
name = "aws-smithy-http-server-python"
version = "0.0.0-smithy-rs-head"
authors = ["Smithy Rust Server <smithy-rs-server@amazon.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
keywords = ["smithy", "framework", "web", "api", "aws"]
categories = ["asynchronous", "web-programming", "api-bindings"]
description = """
Python server runtime for Smithy Rust Server Framework.
"""
# until this is not stable, it is not publishable.
publish = false

[dependencies]
pyo3 = { version = "0.16" }
pyo3-asyncio = { version = "0.16", features = ["attributes", "tokio-runtime"] }
socket2 = { version = "0.4", features = ["all"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
pretty_assertions = "1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
